hydra:
  job_logging:
#    formatters:
#      simple:
#        format: '[]'
    root:
      handlers: [file, console]  # logging to file only.
  run:
    #dir: logs/${dataset}
    dir: logs/${model_type}/${dataset}

model_type: base
dataset: cifar10

data_dir: data

cifar10:
  n_classes: 10

cifar100:
  n_classes: 100

inference: False  # False for training, True for inference.

# training parameters
epochs: 100
n_batch_train: 128
n_batch_test: 200

optimizer: sgd
learning_rate: 0.1
momentum: 0.9
decay: 0.0005

seed: 1234
n_gpu: 1
device: cuda
